# Generated by Django 3.1.3 on 2024-12-23 18:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('installation_date', models.DateTimeField(blank=True, null=True)),
                ('serial_number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DevicesType',
            fields=[
                ('device_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('discount_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'discount',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('service_type', models.CharField(choices=[('Telemovel', 'Telemovel'), ('Internet', 'Internet'), ('TV', 'TV'), ('Telefone', 'Telefone')], max_length=10)),
            ],
            options={
                'db_table': 'plan',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TecnicalVisit',
            fields=[
                ('tecnical_visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('date', models.DateTimeField()),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.device')),
                ('tecnical', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tecnical_visit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('plan_subscription_id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.subscription')),
            ],
            options={
                'db_table': 'plan_subscription',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlanDevice',
            fields=[
                ('plan_device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.device')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.plan')),
            ],
            options={
                'db_table': 'plan_device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('entity', models.TextField(blank=True, null=True)),
                ('refence', models.TextField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.devicestype'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('postal_code', models.TextField()),
                ('country', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubcriptionVisit',
            fields=[
                ('subcription_visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.subscription')),
                ('tecnical_visit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project.tecnicalvisit')),
            ],
            options={
                'db_table': 'subcription_visit',
                'managed': True,
                'unique_together': {('subscription', 'tecnical_visit')},
            },
        ),
    ]
