# Generated by Django 3.1.3 on 2025-01-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
