# Generated by Django 3.1.3 on 2024-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20241219_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestype',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
