# Generated by Django 3.1.3 on 2024-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20241219_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='password',
        ),
        migrations.AlterField(
            model_name='device',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
